---
- name: Update apt cache
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install Apache2
  apt:
    name: "{{ apache_package }}"
    state: present
  notify: Restart Apache

- name: Install PHP and related packages
  apt:
    name: "{{ php_package }}"
    state: present
  notify: Restart Apache

- name: Enable and start Apache
  service:
    name: apache2
    state: started
    enabled: yes
  notify: Restart Apache
